//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIS.SYS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBM_MENU()
        {
            this.Child = new HashSet<TBM_MENU>();
        }
    
        public string ID { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_TYPE { get; set; }
        public int SEQ { get; set; }
        public string PARENT_ID { get; set; }
        public string ICON_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBM_MENU> Child { get; set; }
        public virtual TBM_MENU Parent { get; set; }
    }
}
