//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIS.SYS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_USER
    {
        public string ID { get; set; }
        public string FNAME_EN { get; set; }
        public string LNAME_EN { get; set; }
        public string FNAME_TH { get; set; }
        public string LNAME_TH { get; set; }
        public Nullable<int> POSITION_ID { get; set; }
        public Nullable<int> DIVISION_ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string PASS { get; set; }
        public string CRT_ID { get; set; }
        public System.DateTime CRT_DATE { get; set; }
        public string CRT_MACHINE { get; set; }
        public string UPD_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_MACHINE { get; set; }
        public string DEL_ID { get; set; }
        public Nullable<System.DateTime> DEL_DATE { get; set; }
        public string DEL_MACHINE { get; set; }
        public Nullable<int> PRENAME_ID { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<int> SUBDIVISION_ID { get; set; }
        public string IDCARD { get; set; }
        public byte[] USER_PIC { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string LABSUPERVISOR_NO { get; set; }
    }
}
