//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIS.SYS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_SYSTEM_CONFIG
    {
        public int ID { get; set; }
        public bool IS_UPDATE_AUTOUPDATE { get; set; }
        public string UPD_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_MACHINE { get; set; }
        public string DEFAULT_REPORT_LAB_SUPERVISOR_ID { get; set; }
        public string DEFAULT_REPORT_REGISTRATION_ID { get; set; }
        public string DEFAULT_REPORT_WPA_REGISTRATION_ID { get; set; }
        public string DEFAULT_REPORT_WPA_LAB_SUPERVISOR_ID { get; set; }
        public string REPORT_REV_WPL { get; set; }
        public string REPORT_REV_WPA { get; set; }
    }
}
