//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIS.MAS.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.EntityClient;
    using System.Data.SqlClient;
    using OIS.Common;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OIS_MASEntities : DbContext
    {
    	public static string connectionString
    	{
    		get
    		{
    			SqlConnectionStringBuilder sqlBuilder = new SqlConnectionStringBuilder
    			{
    				MultipleActiveResultSets = true,
    				DataSource =  OISDataInfo.DatabaseInfomation.DATASOURCE,
    				InitialCatalog = OISDataInfo.DatabaseInfomation.DATABASENAME,
    				UserID = OISDataInfo.DatabaseInfomation.USERNAME,
    				Password = OISDataInfo.DatabaseInfomation.PASSWORD,
    			};
    
    			EntityConnectionStringBuilder entityString = new EntityConnectionStringBuilder
                {
                    Provider = "System.Data.SqlClient",
                    Metadata = string.Format("res://*/{0}.csdl|res://*/{0}.ssdl|res://*/{0}.msl", "OIS_MASModel"),
                    ProviderConnectionString = sqlBuilder.ConnectionString,
                };
                return entityString.ConnectionString;
    		}
    	}
        public OIS_MASEntities()
            //: base("name=OIS_MASEntities")
    		: base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBM_DIVISION> TBM_DIVISION { get; set; }
        public virtual DbSet<TBM_GROUP> TBM_GROUP { get; set; }
        public virtual DbSet<TBM_POSITION> TBM_POSITION { get; set; }
        public virtual DbSet<TBM_USER> TBM_USER { get; set; }
        public virtual DbSet<TBM_CONDITION_REPORT_WPL> TBM_CONDITION_REPORT_WPL { get; set; }
    
        public virtual ObjectResult<sp_MAS_ComboGroup_Result> sp_MAS_ComboGroup(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboGroup_Result>("sp_MAS_ComboGroup", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboDivision_Result> sp_MAS_ComboDivision(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboDivision_Result>("sp_MAS_ComboDivision", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboPosition_Result> sp_MAS_ComboPosition(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboPosition_Result>("sp_MAS_ComboPosition", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboSubDivision_Result> sp_MAS_ComboSubDivision(Nullable<int> p_DivisionId, Nullable<bool> p_IncDel)
        {
            var p_DivisionIdParameter = p_DivisionId.HasValue ?
                new ObjectParameter("p_DivisionId", p_DivisionId) :
                new ObjectParameter("p_DivisionId", typeof(int));
    
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboSubDivision_Result>("sp_MAS_ComboSubDivision", p_DivisionIdParameter, p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboPreName_Result> sp_MAS_ComboPreName(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboPreName_Result>("sp_MAS_ComboPreName", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS102_GetDivision_Result> sp_MAS102_GetDivision(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS102_GetDivision_Result>("sp_MAS102_GetDivision", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS102_SaveDivision(Nullable<int> p_ID, string p_NAME_EN, string p_NAME_TH, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS102_SaveDivision", p_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS103_GetSubDivision_Result> sp_MAS103_GetSubDivision(Nullable<int> p_ID, Nullable<int> p_DIVISION_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_DIVISION_IDParameter = p_DIVISION_ID.HasValue ?
                new ObjectParameter("p_DIVISION_ID", p_DIVISION_ID) :
                new ObjectParameter("p_DIVISION_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS103_GetSubDivision_Result>("sp_MAS103_GetSubDivision", p_IDParameter, p_DIVISION_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<sp_MAS104_GetPosition_Result> sp_MAS104_GetPosition(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS104_GetPosition_Result>("sp_MAS104_GetPosition", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<sp_MAS101_GetUser_Result> sp_MAS101_GetUser(string p_ID, string p_NAME, Nullable<int> p_DIVISION_ID, Nullable<int> p_SUBDIVISION_ID, Nullable<int> p_POSITION_ID, Nullable<int> p_GROUP_ID, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID != null ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(string));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_DIVISION_IDParameter = p_DIVISION_ID.HasValue ?
                new ObjectParameter("p_DIVISION_ID", p_DIVISION_ID) :
                new ObjectParameter("p_DIVISION_ID", typeof(int));
    
            var p_SUBDIVISION_IDParameter = p_SUBDIVISION_ID.HasValue ?
                new ObjectParameter("p_SUBDIVISION_ID", p_SUBDIVISION_ID) :
                new ObjectParameter("p_SUBDIVISION_ID", typeof(int));
    
            var p_POSITION_IDParameter = p_POSITION_ID.HasValue ?
                new ObjectParameter("p_POSITION_ID", p_POSITION_ID) :
                new ObjectParameter("p_POSITION_ID", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("P_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("P_GROUP_ID", typeof(int));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS101_GetUser_Result>("sp_MAS101_GetUser", p_IDParameter, p_NAMEParameter, p_DIVISION_IDParameter, p_SUBDIVISION_IDParameter, p_POSITION_IDParameter, p_GROUP_IDParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<string> sp_MAS101_SaveUser(string p_ID, Nullable<int> p_PRENAME_ID, string p_FNAME_EN, string p_LNAME_EN, string p_FNAME_TH, string p_LNAME_TH, string p_NICKNAME, string p_IDCARD, Nullable<System.DateTime> p_BIRTHDATE, Nullable<System.DateTime> p_STARTDATE, Nullable<int> p_DIVISION_ID, Nullable<int> p_SUBDIVISION_ID, Nullable<int> p_POSITION_ID, Nullable<int> p_GROUP_ID, string p_REGISTRATION_NO, string p_LABSUPERVISOR_NO, byte[] p_USER_PIC, string p_PASS, string p_USERID)
        {
            var p_IDParameter = p_ID != null ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(string));
    
            var p_PRENAME_IDParameter = p_PRENAME_ID.HasValue ?
                new ObjectParameter("p_PRENAME_ID", p_PRENAME_ID) :
                new ObjectParameter("p_PRENAME_ID", typeof(int));
    
            var p_FNAME_ENParameter = p_FNAME_EN != null ?
                new ObjectParameter("p_FNAME_EN", p_FNAME_EN) :
                new ObjectParameter("p_FNAME_EN", typeof(string));
    
            var p_LNAME_ENParameter = p_LNAME_EN != null ?
                new ObjectParameter("p_LNAME_EN", p_LNAME_EN) :
                new ObjectParameter("p_LNAME_EN", typeof(string));
    
            var p_FNAME_THParameter = p_FNAME_TH != null ?
                new ObjectParameter("p_FNAME_TH", p_FNAME_TH) :
                new ObjectParameter("p_FNAME_TH", typeof(string));
    
            var p_LNAME_THParameter = p_LNAME_TH != null ?
                new ObjectParameter("p_LNAME_TH", p_LNAME_TH) :
                new ObjectParameter("p_LNAME_TH", typeof(string));
    
            var p_NICKNAMEParameter = p_NICKNAME != null ?
                new ObjectParameter("p_NICKNAME", p_NICKNAME) :
                new ObjectParameter("p_NICKNAME", typeof(string));
    
            var p_IDCARDParameter = p_IDCARD != null ?
                new ObjectParameter("P_IDCARD", p_IDCARD) :
                new ObjectParameter("P_IDCARD", typeof(string));
    
            var p_BIRTHDATEParameter = p_BIRTHDATE.HasValue ?
                new ObjectParameter("p_BIRTHDATE", p_BIRTHDATE) :
                new ObjectParameter("p_BIRTHDATE", typeof(System.DateTime));
    
            var p_STARTDATEParameter = p_STARTDATE.HasValue ?
                new ObjectParameter("p_STARTDATE", p_STARTDATE) :
                new ObjectParameter("p_STARTDATE", typeof(System.DateTime));
    
            var p_DIVISION_IDParameter = p_DIVISION_ID.HasValue ?
                new ObjectParameter("p_DIVISION_ID", p_DIVISION_ID) :
                new ObjectParameter("p_DIVISION_ID", typeof(int));
    
            var p_SUBDIVISION_IDParameter = p_SUBDIVISION_ID.HasValue ?
                new ObjectParameter("p_SUBDIVISION_ID", p_SUBDIVISION_ID) :
                new ObjectParameter("p_SUBDIVISION_ID", typeof(int));
    
            var p_POSITION_IDParameter = p_POSITION_ID.HasValue ?
                new ObjectParameter("p_POSITION_ID", p_POSITION_ID) :
                new ObjectParameter("p_POSITION_ID", typeof(int));
    
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("p_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("p_GROUP_ID", typeof(int));
    
            var p_REGISTRATION_NOParameter = p_REGISTRATION_NO != null ?
                new ObjectParameter("p_REGISTRATION_NO", p_REGISTRATION_NO) :
                new ObjectParameter("p_REGISTRATION_NO", typeof(string));
    
            var p_LABSUPERVISOR_NOParameter = p_LABSUPERVISOR_NO != null ?
                new ObjectParameter("p_LABSUPERVISOR_NO", p_LABSUPERVISOR_NO) :
                new ObjectParameter("p_LABSUPERVISOR_NO", typeof(string));
    
            var p_USER_PICParameter = p_USER_PIC != null ?
                new ObjectParameter("p_USER_PIC", p_USER_PIC) :
                new ObjectParameter("p_USER_PIC", typeof(byte[]));
    
            var p_PASSParameter = p_PASS != null ?
                new ObjectParameter("p_PASS", p_PASS) :
                new ObjectParameter("p_PASS", typeof(string));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_MAS101_SaveUser", p_IDParameter, p_PRENAME_IDParameter, p_FNAME_ENParameter, p_LNAME_ENParameter, p_FNAME_THParameter, p_LNAME_THParameter, p_NICKNAMEParameter, p_IDCARDParameter, p_BIRTHDATEParameter, p_STARTDATEParameter, p_DIVISION_IDParameter, p_SUBDIVISION_IDParameter, p_POSITION_IDParameter, p_GROUP_IDParameter, p_REGISTRATION_NOParameter, p_LABSUPERVISOR_NOParameter, p_USER_PICParameter, p_PASSParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS101_CancelUser(string p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID != null ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(string));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS101_CancelUser", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS301_GetUnit_Result> sp_MAS301_GetUnit(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS301_GetUnit_Result>("sp_MAS301_GetUnit", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS301_SaveUnit(Nullable<int> p_ID, string p_NAME, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS301_SaveUnit", p_IDParameter, p_NAMEParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS301_CancelUnit(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS301_CancelUnit", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS303_CancelInstrument(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS303_CancelInstrument", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS303_GetInstrument_Result> sp_MAS303_GetInstrument(Nullable<int> p_ID, string p_NAME, string p_MODEL, string p_SERIALNO, Nullable<bool> p_SHOWDELETERECORD, Nullable<bool> p_SHOWEXPIRED)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_MODELParameter = p_MODEL != null ?
                new ObjectParameter("p_MODEL", p_MODEL) :
                new ObjectParameter("p_MODEL", typeof(string));
    
            var p_SERIALNOParameter = p_SERIALNO != null ?
                new ObjectParameter("p_SERIALNO", p_SERIALNO) :
                new ObjectParameter("p_SERIALNO", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            var p_SHOWEXPIREDParameter = p_SHOWEXPIRED.HasValue ?
                new ObjectParameter("p_SHOWEXPIRED", p_SHOWEXPIRED) :
                new ObjectParameter("p_SHOWEXPIRED", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS303_GetInstrument_Result>("sp_MAS303_GetInstrument", p_IDParameter, p_NAMEParameter, p_MODELParameter, p_SERIALNOParameter, p_SHOWDELETERECORDParameter, p_SHOWEXPIREDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS303_SaveInstrument(Nullable<int> p_ID, string p_NAME, string p_MODEL, string p_SERIALNO, Nullable<System.DateTime> p_EXPIRE_DATE, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_MODELParameter = p_MODEL != null ?
                new ObjectParameter("p_MODEL", p_MODEL) :
                new ObjectParameter("p_MODEL", typeof(string));
    
            var p_SERIALNOParameter = p_SERIALNO != null ?
                new ObjectParameter("p_SERIALNO", p_SERIALNO) :
                new ObjectParameter("p_SERIALNO", typeof(string));
    
            var p_EXPIRE_DATEParameter = p_EXPIRE_DATE.HasValue ?
                new ObjectParameter("p_EXPIRE_DATE", p_EXPIRE_DATE) :
                new ObjectParameter("p_EXPIRE_DATE", typeof(System.DateTime));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS303_SaveInstrument", p_IDParameter, p_NAMEParameter, p_MODELParameter, p_SERIALNOParameter, p_EXPIRE_DATEParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS203_CancelProvince(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS203_CancelProvince", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS203_GetProvince_Result> sp_MAS203_GetProvince(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS203_GetProvince_Result>("sp_MAS203_GetProvince", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS203_SaveProvince(Nullable<int> p_ID, string p_NAME_EN, string p_NAME_TH, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS203_SaveProvince", p_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS102_CancelDivision(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS102_CancelDivision", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS103_CancelSubDivision(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS103_CancelSubDivision", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS103_SaveSubDivision(Nullable<int> p_ID, Nullable<int> p_DIVISION_ID, string p_NAME_EN, string p_NAME_TH, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_DIVISION_IDParameter = p_DIVISION_ID.HasValue ?
                new ObjectParameter("p_DIVISION_ID", p_DIVISION_ID) :
                new ObjectParameter("p_DIVISION_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS103_SaveSubDivision", p_IDParameter, p_DIVISION_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS104_CancelPosition(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS104_CancelPosition", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS104_SavePosition(Nullable<int> p_ID, string p_NAME_EN, string p_NAME_TH, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS104_SavePosition", p_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS105_CancelPreName(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS105_CancelPreName", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS105_GetPreName_Result> sp_MAS105_GetPreName(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS105_GetPreName_Result>("sp_MAS105_GetPreName", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS105_SavePreName(Nullable<int> p_ID, string p_NAME_EN, string p_NAME_TH, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS105_SavePreName", p_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS106_CancelGroup(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS106_CancelGroup", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS106_GetGroup_Result> sp_MAS106_GetGroup(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS106_GetGroup_Result>("sp_MAS106_GetGroup", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS106_SaveGroup(Nullable<int> p_ID, string p_NAME_EN, string p_NAME_TH, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS106_SaveGroup", p_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS106_GetGroupPermission_Result> sp_MAS106_GetGroupPermission(Nullable<int> p_ID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS106_GetGroupPermission_Result>("sp_MAS106_GetGroupPermission", p_IDParameter);
        }
    
        public virtual ObjectResult<sp_MAS106_GetGroupUser_Result> sp_MAS106_GetGroupUser(Nullable<int> p_ID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS106_GetGroupUser_Result>("sp_MAS106_GetGroupUser", p_IDParameter);
        }
    
        public virtual int sp_MAS106_SaveGroupPermission(Nullable<int> p_GROUP_ID, string p_MENU_ID, Nullable<bool> p_IS_ALLOW, string p_USERID)
        {
            var p_GROUP_IDParameter = p_GROUP_ID.HasValue ?
                new ObjectParameter("p_GROUP_ID", p_GROUP_ID) :
                new ObjectParameter("p_GROUP_ID", typeof(int));
    
            var p_MENU_IDParameter = p_MENU_ID != null ?
                new ObjectParameter("p_MENU_ID", p_MENU_ID) :
                new ObjectParameter("p_MENU_ID", typeof(string));
    
            var p_IS_ALLOWParameter = p_IS_ALLOW.HasValue ?
                new ObjectParameter("p_IS_ALLOW", p_IS_ALLOW) :
                new ObjectParameter("p_IS_ALLOW", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS106_SaveGroupPermission", p_GROUP_IDParameter, p_MENU_IDParameter, p_IS_ALLOWParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS201_GetCustomer_Result> sp_MAS201_GetCustomer(Nullable<int> p_ID, string p_NAME, string p_ADDR, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_ADDRParameter = p_ADDR != null ?
                new ObjectParameter("p_ADDR", p_ADDR) :
                new ObjectParameter("p_ADDR", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS201_GetCustomer_Result>("sp_MAS201_GetCustomer", p_IDParameter, p_NAMEParameter, p_ADDRParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual int sp_MAS201_CancelCustomer(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS201_CancelCustomer", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS201_SaveCustomer(Nullable<int> p_ID, string p_NAME_EN, string p_NAME_TH, string p_ADDR_NO, Nullable<int> p_MOO, string p_BUILDING_EN, string p_BUILDING_TH, string p_ALLEY_EN, string p_ALLEY_TH, string p_LANE_EN, string p_LANE_TH, string p_ROAD_EN, string p_ROAD_TH, string p_SUBDISTRICT_EN, string p_SUBDISTRICT_TH, string p_DISTRICT_EN, string p_DISTRICT_TH, Nullable<int> p_PROVINCE_ID, string p_POSTCODE, string p_COUNTRY, string p_DEFAULT_LANGUAGE, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_ADDR_NOParameter = p_ADDR_NO != null ?
                new ObjectParameter("p_ADDR_NO", p_ADDR_NO) :
                new ObjectParameter("p_ADDR_NO", typeof(string));
    
            var p_MOOParameter = p_MOO.HasValue ?
                new ObjectParameter("p_MOO", p_MOO) :
                new ObjectParameter("p_MOO", typeof(int));
    
            var p_BUILDING_ENParameter = p_BUILDING_EN != null ?
                new ObjectParameter("p_BUILDING_EN", p_BUILDING_EN) :
                new ObjectParameter("p_BUILDING_EN", typeof(string));
    
            var p_BUILDING_THParameter = p_BUILDING_TH != null ?
                new ObjectParameter("p_BUILDING_TH", p_BUILDING_TH) :
                new ObjectParameter("p_BUILDING_TH", typeof(string));
    
            var p_ALLEY_ENParameter = p_ALLEY_EN != null ?
                new ObjectParameter("p_ALLEY_EN", p_ALLEY_EN) :
                new ObjectParameter("p_ALLEY_EN", typeof(string));
    
            var p_ALLEY_THParameter = p_ALLEY_TH != null ?
                new ObjectParameter("p_ALLEY_TH", p_ALLEY_TH) :
                new ObjectParameter("p_ALLEY_TH", typeof(string));
    
            var p_LANE_ENParameter = p_LANE_EN != null ?
                new ObjectParameter("p_LANE_EN", p_LANE_EN) :
                new ObjectParameter("p_LANE_EN", typeof(string));
    
            var p_LANE_THParameter = p_LANE_TH != null ?
                new ObjectParameter("p_LANE_TH", p_LANE_TH) :
                new ObjectParameter("p_LANE_TH", typeof(string));
    
            var p_ROAD_ENParameter = p_ROAD_EN != null ?
                new ObjectParameter("p_ROAD_EN", p_ROAD_EN) :
                new ObjectParameter("p_ROAD_EN", typeof(string));
    
            var p_ROAD_THParameter = p_ROAD_TH != null ?
                new ObjectParameter("p_ROAD_TH", p_ROAD_TH) :
                new ObjectParameter("p_ROAD_TH", typeof(string));
    
            var p_SUBDISTRICT_ENParameter = p_SUBDISTRICT_EN != null ?
                new ObjectParameter("p_SUBDISTRICT_EN", p_SUBDISTRICT_EN) :
                new ObjectParameter("p_SUBDISTRICT_EN", typeof(string));
    
            var p_SUBDISTRICT_THParameter = p_SUBDISTRICT_TH != null ?
                new ObjectParameter("p_SUBDISTRICT_TH", p_SUBDISTRICT_TH) :
                new ObjectParameter("p_SUBDISTRICT_TH", typeof(string));
    
            var p_DISTRICT_ENParameter = p_DISTRICT_EN != null ?
                new ObjectParameter("p_DISTRICT_EN", p_DISTRICT_EN) :
                new ObjectParameter("p_DISTRICT_EN", typeof(string));
    
            var p_DISTRICT_THParameter = p_DISTRICT_TH != null ?
                new ObjectParameter("p_DISTRICT_TH", p_DISTRICT_TH) :
                new ObjectParameter("p_DISTRICT_TH", typeof(string));
    
            var p_PROVINCE_IDParameter = p_PROVINCE_ID.HasValue ?
                new ObjectParameter("p_PROVINCE_ID", p_PROVINCE_ID) :
                new ObjectParameter("p_PROVINCE_ID", typeof(int));
    
            var p_POSTCODEParameter = p_POSTCODE != null ?
                new ObjectParameter("p_POSTCODE", p_POSTCODE) :
                new ObjectParameter("p_POSTCODE", typeof(string));
    
            var p_COUNTRYParameter = p_COUNTRY != null ?
                new ObjectParameter("p_COUNTRY", p_COUNTRY) :
                new ObjectParameter("p_COUNTRY", typeof(string));
    
            var p_DEFAULT_LANGUAGEParameter = p_DEFAULT_LANGUAGE != null ?
                new ObjectParameter("p_DEFAULT_LANGUAGE", p_DEFAULT_LANGUAGE) :
                new ObjectParameter("p_DEFAULT_LANGUAGE", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS201_SaveCustomer", p_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_ADDR_NOParameter, p_MOOParameter, p_BUILDING_ENParameter, p_BUILDING_THParameter, p_ALLEY_ENParameter, p_ALLEY_THParameter, p_LANE_ENParameter, p_LANE_THParameter, p_ROAD_ENParameter, p_ROAD_THParameter, p_SUBDISTRICT_ENParameter, p_SUBDISTRICT_THParameter, p_DISTRICT_ENParameter, p_DISTRICT_THParameter, p_PROVINCE_IDParameter, p_POSTCODEParameter, p_COUNTRYParameter, p_DEFAULT_LANGUAGEParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS202_CancelCustomerProject(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS202_CancelCustomerProject", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS202_GetCustomerProject_Result> sp_MAS202_GetCustomerProject(Nullable<int> p_ID, string p_NAME, string p_ADDR, Nullable<int> p_CUSTOMER_ID, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_ADDRParameter = p_ADDR != null ?
                new ObjectParameter("p_ADDR", p_ADDR) :
                new ObjectParameter("p_ADDR", typeof(string));
    
            var p_CUSTOMER_IDParameter = p_CUSTOMER_ID.HasValue ?
                new ObjectParameter("p_CUSTOMER_ID", p_CUSTOMER_ID) :
                new ObjectParameter("p_CUSTOMER_ID", typeof(int));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS202_GetCustomerProject_Result>("sp_MAS202_GetCustomerProject", p_IDParameter, p_NAMEParameter, p_ADDRParameter, p_CUSTOMER_IDParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS202_SaveCustomerProject(Nullable<int> p_ID, string p_NAME_EN, string p_NAME_TH, string p_ADDR_NO, Nullable<int> p_MOO, string p_BUILDING_EN, string p_BUILDING_TH, string p_ALLEY_EN, string p_ALLEY_TH, string p_LANE_EN, string p_LANE_TH, string p_ROAD_EN, string p_ROAD_TH, string p_SUBDISTRICT_EN, string p_SUBDISTRICT_TH, string p_DISTRICT_EN, string p_DISTRICT_TH, Nullable<int> p_PROVINCE_ID, string p_POSTCODE, string p_DEFAULT_LANGUAGE, Nullable<int> p_CUSTOMER_ID, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAME_ENParameter = p_NAME_EN != null ?
                new ObjectParameter("p_NAME_EN", p_NAME_EN) :
                new ObjectParameter("p_NAME_EN", typeof(string));
    
            var p_NAME_THParameter = p_NAME_TH != null ?
                new ObjectParameter("p_NAME_TH", p_NAME_TH) :
                new ObjectParameter("p_NAME_TH", typeof(string));
    
            var p_ADDR_NOParameter = p_ADDR_NO != null ?
                new ObjectParameter("p_ADDR_NO", p_ADDR_NO) :
                new ObjectParameter("p_ADDR_NO", typeof(string));
    
            var p_MOOParameter = p_MOO.HasValue ?
                new ObjectParameter("p_MOO", p_MOO) :
                new ObjectParameter("p_MOO", typeof(int));
    
            var p_BUILDING_ENParameter = p_BUILDING_EN != null ?
                new ObjectParameter("p_BUILDING_EN", p_BUILDING_EN) :
                new ObjectParameter("p_BUILDING_EN", typeof(string));
    
            var p_BUILDING_THParameter = p_BUILDING_TH != null ?
                new ObjectParameter("p_BUILDING_TH", p_BUILDING_TH) :
                new ObjectParameter("p_BUILDING_TH", typeof(string));
    
            var p_ALLEY_ENParameter = p_ALLEY_EN != null ?
                new ObjectParameter("p_ALLEY_EN", p_ALLEY_EN) :
                new ObjectParameter("p_ALLEY_EN", typeof(string));
    
            var p_ALLEY_THParameter = p_ALLEY_TH != null ?
                new ObjectParameter("p_ALLEY_TH", p_ALLEY_TH) :
                new ObjectParameter("p_ALLEY_TH", typeof(string));
    
            var p_LANE_ENParameter = p_LANE_EN != null ?
                new ObjectParameter("p_LANE_EN", p_LANE_EN) :
                new ObjectParameter("p_LANE_EN", typeof(string));
    
            var p_LANE_THParameter = p_LANE_TH != null ?
                new ObjectParameter("p_LANE_TH", p_LANE_TH) :
                new ObjectParameter("p_LANE_TH", typeof(string));
    
            var p_ROAD_ENParameter = p_ROAD_EN != null ?
                new ObjectParameter("p_ROAD_EN", p_ROAD_EN) :
                new ObjectParameter("p_ROAD_EN", typeof(string));
    
            var p_ROAD_THParameter = p_ROAD_TH != null ?
                new ObjectParameter("p_ROAD_TH", p_ROAD_TH) :
                new ObjectParameter("p_ROAD_TH", typeof(string));
    
            var p_SUBDISTRICT_ENParameter = p_SUBDISTRICT_EN != null ?
                new ObjectParameter("p_SUBDISTRICT_EN", p_SUBDISTRICT_EN) :
                new ObjectParameter("p_SUBDISTRICT_EN", typeof(string));
    
            var p_SUBDISTRICT_THParameter = p_SUBDISTRICT_TH != null ?
                new ObjectParameter("p_SUBDISTRICT_TH", p_SUBDISTRICT_TH) :
                new ObjectParameter("p_SUBDISTRICT_TH", typeof(string));
    
            var p_DISTRICT_ENParameter = p_DISTRICT_EN != null ?
                new ObjectParameter("p_DISTRICT_EN", p_DISTRICT_EN) :
                new ObjectParameter("p_DISTRICT_EN", typeof(string));
    
            var p_DISTRICT_THParameter = p_DISTRICT_TH != null ?
                new ObjectParameter("p_DISTRICT_TH", p_DISTRICT_TH) :
                new ObjectParameter("p_DISTRICT_TH", typeof(string));
    
            var p_PROVINCE_IDParameter = p_PROVINCE_ID.HasValue ?
                new ObjectParameter("p_PROVINCE_ID", p_PROVINCE_ID) :
                new ObjectParameter("p_PROVINCE_ID", typeof(int));
    
            var p_POSTCODEParameter = p_POSTCODE != null ?
                new ObjectParameter("p_POSTCODE", p_POSTCODE) :
                new ObjectParameter("p_POSTCODE", typeof(string));
    
            var p_DEFAULT_LANGUAGEParameter = p_DEFAULT_LANGUAGE != null ?
                new ObjectParameter("p_DEFAULT_LANGUAGE", p_DEFAULT_LANGUAGE) :
                new ObjectParameter("p_DEFAULT_LANGUAGE", typeof(string));
    
            var p_CUSTOMER_IDParameter = p_CUSTOMER_ID.HasValue ?
                new ObjectParameter("p_CUSTOMER_ID", p_CUSTOMER_ID) :
                new ObjectParameter("p_CUSTOMER_ID", typeof(int));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS202_SaveCustomerProject", p_IDParameter, p_NAME_ENParameter, p_NAME_THParameter, p_ADDR_NOParameter, p_MOOParameter, p_BUILDING_ENParameter, p_BUILDING_THParameter, p_ALLEY_ENParameter, p_ALLEY_THParameter, p_LANE_ENParameter, p_LANE_THParameter, p_ROAD_ENParameter, p_ROAD_THParameter, p_SUBDISTRICT_ENParameter, p_SUBDISTRICT_THParameter, p_DISTRICT_ENParameter, p_DISTRICT_THParameter, p_PROVINCE_IDParameter, p_POSTCODEParameter, p_DEFAULT_LANGUAGEParameter, p_CUSTOMER_IDParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboCustomer_Result> sp_MAS_ComboCustomer(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboCustomer_Result>("sp_MAS_ComboCustomer", p_IncDelParameter);
        }
    
        public virtual int sp_MAS302_CancelSTDLight(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS302_CancelSTDLight", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS302_GetSTDLight_Result> sp_MAS302_GetSTDLight(Nullable<int> p_ID, string p_TYPE_NAME, string p_BUILDING_NAME, string p_AREA_NAME, string p_ALIAS_NAME, Nullable<int> p_STANDARD_VALUE, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_TYPE_NAMEParameter = p_TYPE_NAME != null ?
                new ObjectParameter("p_TYPE_NAME", p_TYPE_NAME) :
                new ObjectParameter("p_TYPE_NAME", typeof(string));
    
            var p_BUILDING_NAMEParameter = p_BUILDING_NAME != null ?
                new ObjectParameter("p_BUILDING_NAME", p_BUILDING_NAME) :
                new ObjectParameter("p_BUILDING_NAME", typeof(string));
    
            var p_AREA_NAMEParameter = p_AREA_NAME != null ?
                new ObjectParameter("p_AREA_NAME", p_AREA_NAME) :
                new ObjectParameter("p_AREA_NAME", typeof(string));
    
            var p_ALIAS_NAMEParameter = p_ALIAS_NAME != null ?
                new ObjectParameter("p_ALIAS_NAME", p_ALIAS_NAME) :
                new ObjectParameter("p_ALIAS_NAME", typeof(string));
    
            var p_STANDARD_VALUEParameter = p_STANDARD_VALUE.HasValue ?
                new ObjectParameter("p_STANDARD_VALUE", p_STANDARD_VALUE) :
                new ObjectParameter("p_STANDARD_VALUE", typeof(int));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS302_GetSTDLight_Result>("sp_MAS302_GetSTDLight", p_IDParameter, p_TYPE_NAMEParameter, p_BUILDING_NAMEParameter, p_AREA_NAMEParameter, p_ALIAS_NAMEParameter, p_STANDARD_VALUEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS302_SaveSTDLight(Nullable<int> p_ID, string p_NAME, string p_TYPE_NAME, string p_BUILDING_NAME, string p_ALIAS_NAME, string p_ALIAS_NAME_EN, Nullable<int> p_STANDARD, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_TYPE_NAMEParameter = p_TYPE_NAME != null ?
                new ObjectParameter("p_TYPE_NAME", p_TYPE_NAME) :
                new ObjectParameter("p_TYPE_NAME", typeof(string));
    
            var p_BUILDING_NAMEParameter = p_BUILDING_NAME != null ?
                new ObjectParameter("p_BUILDING_NAME", p_BUILDING_NAME) :
                new ObjectParameter("p_BUILDING_NAME", typeof(string));
    
            var p_ALIAS_NAMEParameter = p_ALIAS_NAME != null ?
                new ObjectParameter("p_ALIAS_NAME", p_ALIAS_NAME) :
                new ObjectParameter("p_ALIAS_NAME", typeof(string));
    
            var p_ALIAS_NAME_ENParameter = p_ALIAS_NAME_EN != null ?
                new ObjectParameter("p_ALIAS_NAME_EN", p_ALIAS_NAME_EN) :
                new ObjectParameter("p_ALIAS_NAME_EN", typeof(string));
    
            var p_STANDARDParameter = p_STANDARD.HasValue ?
                new ObjectParameter("p_STANDARD", p_STANDARD) :
                new ObjectParameter("p_STANDARD", typeof(int));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS302_SaveSTDLight", p_IDParameter, p_NAMEParameter, p_TYPE_NAMEParameter, p_BUILDING_NAMEParameter, p_ALIAS_NAMEParameter, p_ALIAS_NAME_ENParameter, p_STANDARDParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboProvince_Result> sp_MAS_ComboProvince(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboProvince_Result>("sp_MAS_ComboProvince", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboReportCode_Result> sp_MAS_ComboReportCode(string p_REPORT_TYPE)
        {
            var p_REPORT_TYPEParameter = p_REPORT_TYPE != null ?
                new ObjectParameter("p_REPORT_TYPE", p_REPORT_TYPE) :
                new ObjectParameter("p_REPORT_TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboReportCode_Result>("sp_MAS_ComboReportCode", p_REPORT_TYPEParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboCustomerProject_Result> sp_MAS_ComboCustomerProject(Nullable<int> p_CustomerId, Nullable<bool> p_IncDel)
        {
            var p_CustomerIdParameter = p_CustomerId.HasValue ?
                new ObjectParameter("p_CustomerId", p_CustomerId) :
                new ObjectParameter("p_CustomerId", typeof(int));
    
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboCustomerProject_Result>("sp_MAS_ComboCustomerProject", p_CustomerIdParameter, p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboInstrument_Result> sp_MAS_ComboInstrument(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboInstrument_Result>("sp_MAS_ComboInstrument", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboUser_Result> sp_MAS_ComboUser(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboUser_Result>("sp_MAS_ComboUser", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_DialogCustomerLocation_Result> sp_MAS_DialogCustomerLocation(Nullable<int> p_Customer_Id)
        {
            var p_Customer_IdParameter = p_Customer_Id.HasValue ?
                new ObjectParameter("p_Customer_Id", p_Customer_Id) :
                new ObjectParameter("p_Customer_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_DialogCustomerLocation_Result>("sp_MAS_DialogCustomerLocation", p_Customer_IdParameter);
        }
    
        public virtual int sp_MAS306_CancelConditionLight(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS306_CancelConditionLight", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS306_GetConditionLight_Result> sp_MAS306_GetConditionLight(Nullable<int> p_ID, string p_CODE, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_CODEParameter = p_CODE != null ?
                new ObjectParameter("p_CODE", p_CODE) :
                new ObjectParameter("p_CODE", typeof(string));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS306_GetConditionLight_Result>("sp_MAS306_GetConditionLight", p_IDParameter, p_CODEParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS306_SaveConditionLight(Nullable<int> p_ID, string p_CODE, string p_NAME, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_CODEParameter = p_CODE != null ?
                new ObjectParameter("p_CODE", p_CODE) :
                new ObjectParameter("p_CODE", typeof(string));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS306_SaveConditionLight", p_IDParameter, p_CODEParameter, p_NAMEParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS304_CancelMethodAnalysis(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS304_CancelMethodAnalysis", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS304_GetMethodAnalysis_Result> sp_MAS304_GetMethodAnalysis(Nullable<int> p_ID, string p_NAME, Nullable<int> p_INSTITUTION_ID, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_INSTITUTION_IDParameter = p_INSTITUTION_ID.HasValue ?
                new ObjectParameter("p_INSTITUTION_ID", p_INSTITUTION_ID) :
                new ObjectParameter("p_INSTITUTION_ID", typeof(int));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS304_GetMethodAnalysis_Result>("sp_MAS304_GetMethodAnalysis", p_IDParameter, p_NAMEParameter, p_INSTITUTION_IDParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS304_SaveMethodAnalysis(Nullable<int> p_ID, string p_NAME, Nullable<int> p_INSTITUTION_ID, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_INSTITUTION_IDParameter = p_INSTITUTION_ID.HasValue ?
                new ObjectParameter("p_INSTITUTION_ID", p_INSTITUTION_ID) :
                new ObjectParameter("p_INSTITUTION_ID", typeof(int));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS304_SaveMethodAnalysis", p_IDParameter, p_NAMEParameter, p_INSTITUTION_IDParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS305_CancelParameterAnalysis(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS305_CancelParameterAnalysis", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS305_GetParameterAnalysis_Result> sp_MAS305_GetParameterAnalysis(Nullable<int> p_ID, string p_NAME, Nullable<int> p_METHOD_ID, Nullable<int> p_UNIT_ID, Nullable<decimal> p_STANDARD, Nullable<int> p_TOOL_PICK_ID, Nullable<int> p_TOOL_ANALYSYS_ID, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_METHOD_IDParameter = p_METHOD_ID.HasValue ?
                new ObjectParameter("p_METHOD_ID", p_METHOD_ID) :
                new ObjectParameter("p_METHOD_ID", typeof(int));
    
            var p_UNIT_IDParameter = p_UNIT_ID.HasValue ?
                new ObjectParameter("p_UNIT_ID", p_UNIT_ID) :
                new ObjectParameter("p_UNIT_ID", typeof(int));
    
            var p_STANDARDParameter = p_STANDARD.HasValue ?
                new ObjectParameter("p_STANDARD", p_STANDARD) :
                new ObjectParameter("p_STANDARD", typeof(decimal));
    
            var p_TOOL_PICK_IDParameter = p_TOOL_PICK_ID.HasValue ?
                new ObjectParameter("p_TOOL_PICK_ID", p_TOOL_PICK_ID) :
                new ObjectParameter("p_TOOL_PICK_ID", typeof(int));
    
            var p_TOOL_ANALYSYS_IDParameter = p_TOOL_ANALYSYS_ID.HasValue ?
                new ObjectParameter("p_TOOL_ANALYSYS_ID", p_TOOL_ANALYSYS_ID) :
                new ObjectParameter("p_TOOL_ANALYSYS_ID", typeof(int));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS305_GetParameterAnalysis_Result>("sp_MAS305_GetParameterAnalysis", p_IDParameter, p_NAMEParameter, p_METHOD_IDParameter, p_UNIT_IDParameter, p_STANDARDParameter, p_TOOL_PICK_IDParameter, p_TOOL_ANALYSYS_IDParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS305_SaveParameterAnalysis(Nullable<int> p_ID, string p_NAME, string p_ANALYSIS_DETAIL, string p_METHOD_REMARK, Nullable<int> p_METHOD_ID, string p_METHOD_REF, string p_METHOD_REF_NO, Nullable<int> p_UNIT_ID, Nullable<decimal> p_STANDARD_THAI, Nullable<decimal> p_STANDARD_ACGIH, Nullable<bool> p_CEILING_LIMIT, Nullable<decimal> p_MRL_VALUE, Nullable<decimal> p_MRL_VALUE_DIV, Nullable<decimal> p_LOD_VALUE, Nullable<decimal> p_LOD_VALUE_DIV, Nullable<decimal> p_IDL_VALUE, Nullable<int> p_LAB_EXT_ID, Nullable<int> p_TOOL_PICK_ID, Nullable<int> p_TOOL_ANALYSYS_ID, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_ANALYSIS_DETAILParameter = p_ANALYSIS_DETAIL != null ?
                new ObjectParameter("p_ANALYSIS_DETAIL", p_ANALYSIS_DETAIL) :
                new ObjectParameter("p_ANALYSIS_DETAIL", typeof(string));
    
            var p_METHOD_REMARKParameter = p_METHOD_REMARK != null ?
                new ObjectParameter("p_METHOD_REMARK", p_METHOD_REMARK) :
                new ObjectParameter("p_METHOD_REMARK", typeof(string));
    
            var p_METHOD_IDParameter = p_METHOD_ID.HasValue ?
                new ObjectParameter("p_METHOD_ID", p_METHOD_ID) :
                new ObjectParameter("p_METHOD_ID", typeof(int));
    
            var p_METHOD_REFParameter = p_METHOD_REF != null ?
                new ObjectParameter("p_METHOD_REF", p_METHOD_REF) :
                new ObjectParameter("p_METHOD_REF", typeof(string));
    
            var p_METHOD_REF_NOParameter = p_METHOD_REF_NO != null ?
                new ObjectParameter("p_METHOD_REF_NO", p_METHOD_REF_NO) :
                new ObjectParameter("p_METHOD_REF_NO", typeof(string));
    
            var p_UNIT_IDParameter = p_UNIT_ID.HasValue ?
                new ObjectParameter("p_UNIT_ID", p_UNIT_ID) :
                new ObjectParameter("p_UNIT_ID", typeof(int));
    
            var p_STANDARD_THAIParameter = p_STANDARD_THAI.HasValue ?
                new ObjectParameter("p_STANDARD_THAI", p_STANDARD_THAI) :
                new ObjectParameter("p_STANDARD_THAI", typeof(decimal));
    
            var p_STANDARD_ACGIHParameter = p_STANDARD_ACGIH.HasValue ?
                new ObjectParameter("p_STANDARD_ACGIH", p_STANDARD_ACGIH) :
                new ObjectParameter("p_STANDARD_ACGIH", typeof(decimal));
    
            var p_CEILING_LIMITParameter = p_CEILING_LIMIT.HasValue ?
                new ObjectParameter("p_CEILING_LIMIT", p_CEILING_LIMIT) :
                new ObjectParameter("p_CEILING_LIMIT", typeof(bool));
    
            var p_MRL_VALUEParameter = p_MRL_VALUE.HasValue ?
                new ObjectParameter("p_MRL_VALUE", p_MRL_VALUE) :
                new ObjectParameter("p_MRL_VALUE", typeof(decimal));
    
            var p_MRL_VALUE_DIVParameter = p_MRL_VALUE_DIV.HasValue ?
                new ObjectParameter("p_MRL_VALUE_DIV", p_MRL_VALUE_DIV) :
                new ObjectParameter("p_MRL_VALUE_DIV", typeof(decimal));
    
            var p_LOD_VALUEParameter = p_LOD_VALUE.HasValue ?
                new ObjectParameter("p_LOD_VALUE", p_LOD_VALUE) :
                new ObjectParameter("p_LOD_VALUE", typeof(decimal));
    
            var p_LOD_VALUE_DIVParameter = p_LOD_VALUE_DIV.HasValue ?
                new ObjectParameter("p_LOD_VALUE_DIV", p_LOD_VALUE_DIV) :
                new ObjectParameter("p_LOD_VALUE_DIV", typeof(decimal));
    
            var p_IDL_VALUEParameter = p_IDL_VALUE.HasValue ?
                new ObjectParameter("p_IDL_VALUE", p_IDL_VALUE) :
                new ObjectParameter("p_IDL_VALUE", typeof(decimal));
    
            var p_LAB_EXT_IDParameter = p_LAB_EXT_ID.HasValue ?
                new ObjectParameter("p_LAB_EXT_ID", p_LAB_EXT_ID) :
                new ObjectParameter("p_LAB_EXT_ID", typeof(int));
    
            var p_TOOL_PICK_IDParameter = p_TOOL_PICK_ID.HasValue ?
                new ObjectParameter("p_TOOL_PICK_ID", p_TOOL_PICK_ID) :
                new ObjectParameter("p_TOOL_PICK_ID", typeof(int));
    
            var p_TOOL_ANALYSYS_IDParameter = p_TOOL_ANALYSYS_ID.HasValue ?
                new ObjectParameter("p_TOOL_ANALYSYS_ID", p_TOOL_ANALYSYS_ID) :
                new ObjectParameter("p_TOOL_ANALYSYS_ID", typeof(int));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS305_SaveParameterAnalysis", p_IDParameter, p_NAMEParameter, p_ANALYSIS_DETAILParameter, p_METHOD_REMARKParameter, p_METHOD_IDParameter, p_METHOD_REFParameter, p_METHOD_REF_NOParameter, p_UNIT_IDParameter, p_STANDARD_THAIParameter, p_STANDARD_ACGIHParameter, p_CEILING_LIMITParameter, p_MRL_VALUEParameter, p_MRL_VALUE_DIVParameter, p_LOD_VALUEParameter, p_LOD_VALUE_DIVParameter, p_IDL_VALUEParameter, p_LAB_EXT_IDParameter, p_TOOL_PICK_IDParameter, p_TOOL_ANALYSYS_IDParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS307_CancelInstitutionSTD(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS307_CancelInstitutionSTD", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS307_GetInstitutionSTD_Result> sp_MAS307_GetInstitutionSTD(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS307_GetInstitutionSTD_Result>("sp_MAS307_GetInstitutionSTD", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS307_SaveInstitutionSTD(Nullable<int> p_ID, string p_NAME, string p_SHORT_NAME, string p_EDITION_NAME, Nullable<int> p_PAGE_FROM, Nullable<int> p_PAGE_TO, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHORT_NAMEParameter = p_SHORT_NAME != null ?
                new ObjectParameter("p_SHORT_NAME", p_SHORT_NAME) :
                new ObjectParameter("p_SHORT_NAME", typeof(string));
    
            var p_EDITION_NAMEParameter = p_EDITION_NAME != null ?
                new ObjectParameter("p_EDITION_NAME", p_EDITION_NAME) :
                new ObjectParameter("p_EDITION_NAME", typeof(string));
    
            var p_PAGE_FROMParameter = p_PAGE_FROM.HasValue ?
                new ObjectParameter("p_PAGE_FROM", p_PAGE_FROM) :
                new ObjectParameter("p_PAGE_FROM", typeof(int));
    
            var p_PAGE_TOParameter = p_PAGE_TO.HasValue ?
                new ObjectParameter("p_PAGE_TO", p_PAGE_TO) :
                new ObjectParameter("p_PAGE_TO", typeof(int));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS307_SaveInstitutionSTD", p_IDParameter, p_NAMEParameter, p_SHORT_NAMEParameter, p_EDITION_NAMEParameter, p_PAGE_FROMParameter, p_PAGE_TOParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboInstitutionSTD_Result> sp_MAS_ComboInstitutionSTD(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboInstitutionSTD_Result>("sp_MAS_ComboInstitutionSTD", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboUnit_Result> sp_MAS_ComboUnit(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboUnit_Result>("sp_MAS_ComboUnit", p_IncDelParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboLabExt_Result> sp_MAS_ComboLabExt(Nullable<bool> p_IncDel)
        {
            var p_IncDelParameter = p_IncDel.HasValue ?
                new ObjectParameter("p_IncDel", p_IncDel) :
                new ObjectParameter("p_IncDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboLabExt_Result>("sp_MAS_ComboLabExt", p_IncDelParameter);
        }
    
        public virtual int sp_MAS310_CancelLabExt(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS310_CancelLabExt", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS310_GetLabExt_Result> sp_MAS310_GetLabExt(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS310_GetLabExt_Result>("sp_MAS310_GetLabExt", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS310_SaveLabExt(Nullable<int> p_ID, string p_NAME, string p_REMARK_NAME, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_REMARK_NAMEParameter = p_REMARK_NAME != null ?
                new ObjectParameter("p_REMARK_NAME", p_REMARK_NAME) :
                new ObjectParameter("p_REMARK_NAME", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS310_SaveLabExt", p_IDParameter, p_NAMEParameter, p_REMARK_NAMEParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS308_CancelToolPick(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS308_CancelToolPick", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS308_GetToolPick_Result> sp_MAS308_GetToolPick(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS308_GetToolPick_Result>("sp_MAS308_GetToolPick", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS308_SaveToolPick(Nullable<int> p_ID, string p_NAME, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS308_SaveToolPick", p_IDParameter, p_NAMEParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual int sp_MAS309_CancelToolAnalysis(Nullable<int> p_ID, Nullable<bool> p_ISCANCEL, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_ISCANCELParameter = p_ISCANCEL.HasValue ?
                new ObjectParameter("p_ISCANCEL", p_ISCANCEL) :
                new ObjectParameter("p_ISCANCEL", typeof(bool));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MAS309_CancelToolAnalysis", p_IDParameter, p_ISCANCELParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS309_GetToolAnalysis_Result> sp_MAS309_GetToolAnalysis(Nullable<int> p_ID, string p_NAME, Nullable<bool> p_SHOWDELETERECORD)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SHOWDELETERECORDParameter = p_SHOWDELETERECORD.HasValue ?
                new ObjectParameter("p_SHOWDELETERECORD", p_SHOWDELETERECORD) :
                new ObjectParameter("p_SHOWDELETERECORD", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS309_GetToolAnalysis_Result>("sp_MAS309_GetToolAnalysis", p_IDParameter, p_NAMEParameter, p_SHOWDELETERECORDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MAS309_SaveToolAnalysis(Nullable<int> p_ID, string p_NAME, Nullable<int> p_SEQ, string p_USERID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("p_ID", p_ID) :
                new ObjectParameter("p_ID", typeof(int));
    
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("p_NAME", p_NAME) :
                new ObjectParameter("p_NAME", typeof(string));
    
            var p_SEQParameter = p_SEQ.HasValue ?
                new ObjectParameter("p_SEQ", p_SEQ) :
                new ObjectParameter("p_SEQ", typeof(int));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MAS309_SaveToolAnalysis", p_IDParameter, p_NAMEParameter, p_SEQParameter, p_USERIDParameter);
        }
    
        public virtual ObjectResult<sp_MAS_ComboLanguage_Result> sp_MAS_ComboLanguage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MAS_ComboLanguage_Result>("sp_MAS_ComboLanguage");
        }
    }
}
