//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIS.SYS.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.EntityClient;
    using System.Data.SqlClient;
    using OIS.Common;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OIS_SYSEntities : DbContext
    {
    	public static string connectionString
    	{
    		get
    		{
    			SqlConnectionStringBuilder sqlBuilder = new SqlConnectionStringBuilder
    			{
    				MultipleActiveResultSets = true,
    				DataSource =  OISDataInfo.DatabaseInfomation.DATASOURCE,
    				InitialCatalog = OISDataInfo.DatabaseInfomation.DATABASENAME,
    				UserID = OISDataInfo.DatabaseInfomation.USERNAME,
    				Password = OISDataInfo.DatabaseInfomation.PASSWORD,
    			};
    
    			EntityConnectionStringBuilder entityString = new EntityConnectionStringBuilder
                {
                    Provider = "System.Data.SqlClient",
                    Metadata = string.Format("res://*/{0}.csdl|res://*/{0}.ssdl|res://*/{0}.msl", "OIS_SYSModel"),
                    ProviderConnectionString = sqlBuilder.ConnectionString,
                };
                return entityString.ConnectionString;
    		}
    	}
        public OIS_SYSEntities()
            //: base("name=OIS_SYSEntities")
    		: base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBM_USER> TBM_USER { get; set; }
        public virtual DbSet<TBM_MENU> TBM_MENU { get; set; }
        public virtual DbSet<TBS_SYSTEM_CONFIG> TBS_SYSTEM_CONFIG { get; set; }
    
        public virtual ObjectResult<sp_SYS_GetMenu_Result> sp_SYS_GetMenu(string p_UserId)
        {
            var p_UserIdParameter = p_UserId != null ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SYS_GetMenu_Result>("sp_SYS_GetMenu", p_UserIdParameter);
        }
    
        public virtual ObjectResult<sp_SYS_UserLogin_Result> sp_SYS_UserLogin(string p_UserName, string p_Password, string p_AppVersion)
        {
            var p_UserNameParameter = p_UserName != null ?
                new ObjectParameter("p_UserName", p_UserName) :
                new ObjectParameter("p_UserName", typeof(string));
    
            var p_PasswordParameter = p_Password != null ?
                new ObjectParameter("p_Password", p_Password) :
                new ObjectParameter("p_Password", typeof(string));
    
            var p_AppVersionParameter = p_AppVersion != null ?
                new ObjectParameter("p_AppVersion", p_AppVersion) :
                new ObjectParameter("p_AppVersion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SYS_UserLogin_Result>("sp_SYS_UserLogin", p_UserNameParameter, p_PasswordParameter, p_AppVersionParameter);
        }
    
        public virtual ObjectResult<sp_SYS02_GetUserProfile_Result> sp_SYS02_GetUserProfile(string p_UserId)
        {
            var p_UserIdParameter = p_UserId != null ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SYS02_GetUserProfile_Result>("sp_SYS02_GetUserProfile", p_UserIdParameter);
        }
    
        public virtual int sp_SYS02_SaveUserProfile(string p_UserId, Nullable<int> p_PreNameId, string p_FName_En, string p_LName_En, string p_FName_Th, string p_LName_Th, string p_NickName, string p_IdCard, Nullable<System.DateTime> p_BirthDate, Nullable<System.DateTime> p_StartDate, Nullable<int> p_DivisionId, Nullable<int> p_SubDivisionId, Nullable<int> p_PositionId, Nullable<int> p_GroupId, string p_RegistrationNo, string p_LabSupervisorNo, byte[] p_UserPic, string p_Password, string p_PasswordNew, string p_PasswordConfirm, string p_UserLogin)
        {
            var p_UserIdParameter = p_UserId != null ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(string));
    
            var p_PreNameIdParameter = p_PreNameId.HasValue ?
                new ObjectParameter("p_PreNameId", p_PreNameId) :
                new ObjectParameter("p_PreNameId", typeof(int));
    
            var p_FName_EnParameter = p_FName_En != null ?
                new ObjectParameter("p_FName_En", p_FName_En) :
                new ObjectParameter("p_FName_En", typeof(string));
    
            var p_LName_EnParameter = p_LName_En != null ?
                new ObjectParameter("p_LName_En", p_LName_En) :
                new ObjectParameter("p_LName_En", typeof(string));
    
            var p_FName_ThParameter = p_FName_Th != null ?
                new ObjectParameter("p_FName_Th", p_FName_Th) :
                new ObjectParameter("p_FName_Th", typeof(string));
    
            var p_LName_ThParameter = p_LName_Th != null ?
                new ObjectParameter("p_LName_Th", p_LName_Th) :
                new ObjectParameter("p_LName_Th", typeof(string));
    
            var p_NickNameParameter = p_NickName != null ?
                new ObjectParameter("p_NickName", p_NickName) :
                new ObjectParameter("p_NickName", typeof(string));
    
            var p_IdCardParameter = p_IdCard != null ?
                new ObjectParameter("p_IdCard", p_IdCard) :
                new ObjectParameter("p_IdCard", typeof(string));
    
            var p_BirthDateParameter = p_BirthDate.HasValue ?
                new ObjectParameter("p_BirthDate", p_BirthDate) :
                new ObjectParameter("p_BirthDate", typeof(System.DateTime));
    
            var p_StartDateParameter = p_StartDate.HasValue ?
                new ObjectParameter("p_StartDate", p_StartDate) :
                new ObjectParameter("p_StartDate", typeof(System.DateTime));
    
            var p_DivisionIdParameter = p_DivisionId.HasValue ?
                new ObjectParameter("p_DivisionId", p_DivisionId) :
                new ObjectParameter("p_DivisionId", typeof(int));
    
            var p_SubDivisionIdParameter = p_SubDivisionId.HasValue ?
                new ObjectParameter("p_SubDivisionId", p_SubDivisionId) :
                new ObjectParameter("p_SubDivisionId", typeof(int));
    
            var p_PositionIdParameter = p_PositionId.HasValue ?
                new ObjectParameter("p_PositionId", p_PositionId) :
                new ObjectParameter("p_PositionId", typeof(int));
    
            var p_GroupIdParameter = p_GroupId.HasValue ?
                new ObjectParameter("p_GroupId", p_GroupId) :
                new ObjectParameter("p_GroupId", typeof(int));
    
            var p_RegistrationNoParameter = p_RegistrationNo != null ?
                new ObjectParameter("p_RegistrationNo", p_RegistrationNo) :
                new ObjectParameter("p_RegistrationNo", typeof(string));
    
            var p_LabSupervisorNoParameter = p_LabSupervisorNo != null ?
                new ObjectParameter("p_LabSupervisorNo", p_LabSupervisorNo) :
                new ObjectParameter("p_LabSupervisorNo", typeof(string));
    
            var p_UserPicParameter = p_UserPic != null ?
                new ObjectParameter("p_UserPic", p_UserPic) :
                new ObjectParameter("p_UserPic", typeof(byte[]));
    
            var p_PasswordParameter = p_Password != null ?
                new ObjectParameter("p_Password", p_Password) :
                new ObjectParameter("p_Password", typeof(string));
    
            var p_PasswordNewParameter = p_PasswordNew != null ?
                new ObjectParameter("p_PasswordNew", p_PasswordNew) :
                new ObjectParameter("p_PasswordNew", typeof(string));
    
            var p_PasswordConfirmParameter = p_PasswordConfirm != null ?
                new ObjectParameter("p_PasswordConfirm", p_PasswordConfirm) :
                new ObjectParameter("p_PasswordConfirm", typeof(string));
    
            var p_UserLoginParameter = p_UserLogin != null ?
                new ObjectParameter("p_UserLogin", p_UserLogin) :
                new ObjectParameter("p_UserLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SYS02_SaveUserProfile", p_UserIdParameter, p_PreNameIdParameter, p_FName_EnParameter, p_LName_EnParameter, p_FName_ThParameter, p_LName_ThParameter, p_NickNameParameter, p_IdCardParameter, p_BirthDateParameter, p_StartDateParameter, p_DivisionIdParameter, p_SubDivisionIdParameter, p_PositionIdParameter, p_GroupIdParameter, p_RegistrationNoParameter, p_LabSupervisorNoParameter, p_UserPicParameter, p_PasswordParameter, p_PasswordNewParameter, p_PasswordConfirmParameter, p_UserLoginParameter);
        }
    
        public virtual ObjectResult<sp_SYS001_GetSystemConfig_Result> sp_SYS001_GetSystemConfig()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SYS001_GetSystemConfig_Result>("sp_SYS001_GetSystemConfig");
        }
    
        public virtual int sp_SYS001_SaveSystemConfig(Nullable<bool> p_IS_UPDATE_AUTOUPDATE, string p_DEFAULT_REPORT_REGISTRATION_ID, string p_DEFAULT_REPORT_LAB_SUPERVISOR_ID, string p_REPORT_REV_WPL, string p_DEFAULT_REPORT_WPA_REGISTRATION_ID, string p_DEFAULT_REPORT_WPA_LAB_SUPERVISOR_ID, string p_REPORT_REV_WPA, string p_USERID)
        {
            var p_IS_UPDATE_AUTOUPDATEParameter = p_IS_UPDATE_AUTOUPDATE.HasValue ?
                new ObjectParameter("p_IS_UPDATE_AUTOUPDATE", p_IS_UPDATE_AUTOUPDATE) :
                new ObjectParameter("p_IS_UPDATE_AUTOUPDATE", typeof(bool));
    
            var p_DEFAULT_REPORT_REGISTRATION_IDParameter = p_DEFAULT_REPORT_REGISTRATION_ID != null ?
                new ObjectParameter("p_DEFAULT_REPORT_REGISTRATION_ID", p_DEFAULT_REPORT_REGISTRATION_ID) :
                new ObjectParameter("p_DEFAULT_REPORT_REGISTRATION_ID", typeof(string));
    
            var p_DEFAULT_REPORT_LAB_SUPERVISOR_IDParameter = p_DEFAULT_REPORT_LAB_SUPERVISOR_ID != null ?
                new ObjectParameter("p_DEFAULT_REPORT_LAB_SUPERVISOR_ID", p_DEFAULT_REPORT_LAB_SUPERVISOR_ID) :
                new ObjectParameter("p_DEFAULT_REPORT_LAB_SUPERVISOR_ID", typeof(string));
    
            var p_REPORT_REV_WPLParameter = p_REPORT_REV_WPL != null ?
                new ObjectParameter("p_REPORT_REV_WPL", p_REPORT_REV_WPL) :
                new ObjectParameter("p_REPORT_REV_WPL", typeof(string));
    
            var p_DEFAULT_REPORT_WPA_REGISTRATION_IDParameter = p_DEFAULT_REPORT_WPA_REGISTRATION_ID != null ?
                new ObjectParameter("p_DEFAULT_REPORT_WPA_REGISTRATION_ID", p_DEFAULT_REPORT_WPA_REGISTRATION_ID) :
                new ObjectParameter("p_DEFAULT_REPORT_WPA_REGISTRATION_ID", typeof(string));
    
            var p_DEFAULT_REPORT_WPA_LAB_SUPERVISOR_IDParameter = p_DEFAULT_REPORT_WPA_LAB_SUPERVISOR_ID != null ?
                new ObjectParameter("p_DEFAULT_REPORT_WPA_LAB_SUPERVISOR_ID", p_DEFAULT_REPORT_WPA_LAB_SUPERVISOR_ID) :
                new ObjectParameter("p_DEFAULT_REPORT_WPA_LAB_SUPERVISOR_ID", typeof(string));
    
            var p_REPORT_REV_WPAParameter = p_REPORT_REV_WPA != null ?
                new ObjectParameter("p_REPORT_REV_WPA", p_REPORT_REV_WPA) :
                new ObjectParameter("p_REPORT_REV_WPA", typeof(string));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("p_USERID", p_USERID) :
                new ObjectParameter("p_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SYS001_SaveSystemConfig", p_IS_UPDATE_AUTOUPDATEParameter, p_DEFAULT_REPORT_REGISTRATION_IDParameter, p_DEFAULT_REPORT_LAB_SUPERVISOR_IDParameter, p_REPORT_REV_WPLParameter, p_DEFAULT_REPORT_WPA_REGISTRATION_IDParameter, p_DEFAULT_REPORT_WPA_LAB_SUPERVISOR_IDParameter, p_REPORT_REV_WPAParameter, p_USERIDParameter);
        }
    
        public virtual int sp_SYS_UserLogout(string p_UserName)
        {
            var p_UserNameParameter = p_UserName != null ?
                new ObjectParameter("p_UserName", p_UserName) :
                new ObjectParameter("p_UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SYS_UserLogout", p_UserNameParameter);
        }
    }
}
