//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIS.MAS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_POSITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBM_POSITION()
        {
            this.TBM_USER = new HashSet<TBM_USER>();
        }
    
        public int ID { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_TH { get; set; }
        public int SEQ { get; set; }
        public string CRT_ID { get; set; }
        public System.DateTime CRT_DATE { get; set; }
        public string CRT_MACHINE { get; set; }
        public string UPD_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPD_MACHINE { get; set; }
        public string DEL_ID { get; set; }
        public Nullable<System.DateTime> DEL_DATE { get; set; }
        public string DEL_MACHINE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBM_USER> TBM_USER { get; set; }
    }
}
