//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIS.RPT.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBR_WORK_PLACE_LIGHT_USER
    {
        public int ID { get; set; }
        public string MEASURED_BY { get; set; }
    }
}
